### ISSUE TITLE
Download whole issue of a Journal

### ISSUE THREAD

**Issue by LlGC-szw** [UniversalViewer/user-stories#1]
## So that I can view the whole issue of that Journal without accessing the website.

**Comment by LlGC-szw** [comment]
Example: http://universalviewer.io/uv.html?manifest=https://www.llgc.org.uk/rhannu/TestScif2176035.json

**Comment by tomcrane** [comment]
Hi Sara,

For the whole sequence, the UV already does this, as can be seen in the example above:

![image](https://user-images.githubusercontent.com/1443575/32504615-2bf64482-c3d8-11e7-9107-08c8b2e487e6.png)

This is done by linking to the PDF using the `rendering` property on the sequence - from the example:

```
"rendering": {
     "@id": "http://datasyllwr.llgc.org.uk/2176035.pdf",
      "format": "application/pdf",
      "label": "Download Llyfr I Ionawr 1895 PDF"
   }
```

Is this story already handled, in your opinion? Or is there an alternative UI for this?

**Comment by LlGC-szw** [comment]
After seeing this working today the download facility looks like it satisfies the user story. I've sent this to the whole team for full approval. Just need to add in the 'terms and conditions' section (in the manifest/theme/config?).

**Comment by tomcrane** [comment]
That last comment (terms and conditions) is user story 3 - have I got that right? The user needs to be able to see the terms of use of the PDF before downloading it?

**Comment by LlGC-szw** [comment]
Yes. How we define 'before downloading' is something to discuss!

**Comment by tomcrane** [comment]
Yes, we might want to use Thursday's community call for that? I'm feeling that this apparently simple requirement might be tricky. I'll add some comments to story 3.

**Comment by LlGC-szw** [comment]
Good idea. I'll post the links on slack for the community call now.

**Comment by LlGC-szw** [comment]
We met this monring and we are happy that the download function meets the acceptance criteria for this as it stands.
